In [1]:
import pandas as pd

In [2]:
# region_code = pd.read_csv('Area to station final.csv')
# region_code.head()

In [3]:
region_code = pd.read_csv('Rate.csv')
region_code.head()

,CATEGORY,AREA_CD,AREA_NM,TOT_REG_CD,ADM_NM,ADM_CD,REG_AREA,AREA,RATE,Area to st,Area to _1
0,인구밀집지역,POI013,가산디지털단지역,1118051010001,가산동,1118051,23090.98,23088.446,1.0,437.0,광명
1,인구밀집지역,POI013,가산디지털단지역,1118051010003,가산동,1118051,215886.15,215871.596,1.0,437.0,광명
2,인구밀집지역,POI013,가산디지털단지역,1118051010002,가산동,1118051,15779.28,15778.026,1.0,437.0,광명
3,인구밀집지역,POI013,가산디지털단지역,1118051010004,가산동,1118051,18596.58,18595.490,1.0,437.0,광명
4,인구밀집지역,POI013,가산디지털단지역,1118051020002,가산동,1118051,736729.26,736705.000,1.0,437.0,광명

In [4]:
lpd_2020 = pd.read_csv('LPD2020_target_final.csv')
lpd_2020.head()

,Unnamed: 0,시간대구분,행정동코드,총생활인구수,10gen_male,10gen_female,20gen_male,20gen_female,30gen_male,30gen_female,40gen_male,40gen_female,50gen_male,50gen_female,60gen_male,60gen_female
0,20200101,0,11230650,40611.2228,1173.7437,1280.1970,2750.7888,2861.4412,4157.2937,3811.1231,3577.0630,3153.0782,2939.9432,2900.4459,2290.8387,2597.0113
1,20200101,0,11305630,35198.4322,1878.1179,1699.8258,4475.8499,4317.8533,2979.7216,2170.2058,2494.1867,2103.3082,2356.9491,2426.6451,1435.7873,1911.3290
2,20200101,0,11470510,40940.3088,3959.6137,3618.8900,2366.5910,2299.0836,2278.1653,2471.9439,4121.1247,4074.6937,2783.6607,2727.6017,1627.9080,1959.0610
3,20200101,0,11710642,36093.9318,963.9956,1025.2427,2863.5148,3141.7070,4728.1644,4147.4601,3463.2023,2890.3202,2408.4137,2286.2820,1713.3264,1845.4484
4,20200101,0,11110640,18507.3315,570.9560,691.8816,1921.2955,2262.4269,1687.5455,1767.6509,1497.8115,1216.3569,1177.9472,1212.8317,821.5251,1013.4862

In [5]:
area = ['삼각지역', '군자역', '회기역', '용산역']
cols = ['TOT_REG_CD','AREA_NM', 'ADM_CD', 'RATE']
region_code_edit = region_code.loc[region_code['AREA_NM'].isin(area), cols]
region_code_edit

        TOT_REG_CD AREA_NM   ADM_CD   RATE
61   1105054010001     군자역  1105054  1.000
62   1105054010002     군자역  1105054  0.489
63   1105054030003     군자역  1105054  0.761
64   1105054030009     군자역  1105054  1.000
65   1105055020004     군자역  1105055  0.647
66   1105056020032     군자역  1105056  0.882
67   1105056020028     군자역  1105056  1.000
68   1105056020007     군자역  1105056  0.537
69   1105056020003     군자역  1105056  0.327
70   1105059010019     군자역  1105059  0.791
71   1105059010013     군자역  1105059  0.996
72   1105059010012     군자역  1105059  0.750
73   1105059010014     군자역  1105059  0.168
74   1105059010016     군자역  1105059  0.386
203  1103073010202    삼각지역  1103073  0.538
204  1103073010201    삼각지역  1103073  0.145
205  1103073020003    삼각지역  1103073  0.062
206  1103073030005    삼각지역  1103073  0.408
207  1103073030004    삼각지역  1103073  0.010
402  1103057020001     용산역  1103057  0.397
403  1103064010001     용산역  1103064  0.238
404  1103072040003     용산역  1103072  0.302
405  1103073020003     용산역  1103073  0.271
406  1103073020004     용산역  1103073  0.928
507  1106071010009     회기역  1106071  1.000
508  1106071010002     회기역  1106071  0.151
509  1106071010005     회기역  1106071  1.000
510  1106071010004     회기역  1106071  0.853
511  1106071010007     회기역  1106071  1.000
512  1106071020006     회기역  1106071  0.679
513  1106071020007     회기역  1106071  0.253
514  1106071020001     회기역  1106071  0.478
515  1106072040006     회기역  1106072  0.948
516  1106072040007     회기역  1106072  0.991
517  1106072040001     회기역  1106072  0.653
518  1106072040014     회기역  1106072  1.000
519  1106072040008     회기역  1106072  0.767
520  1106072040010     회기역  1106072  0.249
521  1106072040013     회기역  1106072  0.855
522  1106072050001     회기역  1106072  0.606
523  1106073010002     회기역  1106073  0.657
524  1106073010009     회기역  1106073  0.506
525  1106089060001     회기역  1106089  0.269
526  1106089060007     회기역  1106089  0.052

In [6]:
merged_df = pd.merge(lpd_2020, region_code_edit, left_on='행정동코드', right_on='ADM code', how='inner')
merged_df.head()

KeyError: 'ADM code'

In [11]:
adm_codes = region_code_edit['ADM code'].tolist()
lpd_2020_filtered = lpd_2020[lpd_2020['행정동코드'].isin(adm_codes)]
lpd_2020_filtered['행정동코드'].value_counts()

행정동코드
11170625    8784
11230710    8784
11215780    8784
Name: count, dtype: int64